### ISSUE TITLE
New User Form (REVISIT AFTER MVP)

### ISSUE THREAD

**Issue by dstarrtrey** [kaibili01/gogitrs#15]
(To be submitted to database)  
- [x] Name 
- [x] Username
- [x] Password
- [x] Location (Possible call to outside API for verification?)
- [x] Account type: **Reaper** or **Sower**
(If sower, user is prompted with these questions)
- [x] Types of yields
- [x] Collection policy (% kept, keep a finished product, etc)
- [x] Currently available for Reaper requests?

**Comment by DDumas551** [comment]
How should we be building these? In backend to be rendered or in the HTML
